### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by chokkoretto** [facebook/fbctf#138]
Hi there,

When running this 
 ./extra/provision.sh -m prod -s $PWD

It ends up with this
[+] Installing composer
/var/www/fbctf/extra/lib.sh: line 229: curl: command not found
Notice: File could not be loaded: composer.phar

Is this an issue?  Because immediately after this, I try to set password and it returns

set_password new_password ctf ctf fbctf $PWD
set_password: command not found

Thanks!

**Comment by gsingh93** [comment]
Are you installing this in a VM or on a physical Ubuntu 14.04 machine?

It seems that some machines do not have curl installed by default, even though the Vagrant VM definitely does. We should probably install curl in the provision script.

**Comment by chokkoretto** [comment]
This is a physical machine.  So should this simply be an install for curl to correct this?

**Comment by gsingh93** [comment]
Yea, installing curl before running the provision script should fix it. Just so we can understand which Ubuntu versions have this issue, can you please give me the output of the following commands:

```
uname -a
lsb_release -a
```

Did you setup the server with the Ubuntu Server image or the Desktop image?

**Comment by mehnomy** [comment]
@chokkoretto 

I have a guide which goes the requirements needed to install this on a Ubuntu 14.04x 64bit for both Server Image and Desktop Image.

[The Guide](https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki)

Please follow the guide step by step, if you have any issues please reply back here.

Regards,
Byron

**Comment by chokkoretto** [comment]
@gsingh93, I am not sure what you mean by Server/Desktop image?  

uname -a
Linux fbctftraining 3.13.0-87-generic #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

@mehnomy thank you, I will look at this!

**Comment by gsingh93** [comment]
@chokkoretto Ubuntu provides both a [server](http://www.ubuntu.com/server) and [desktop](http://www.ubuntu.com/desktop) release. I'm wondering if one of those two doesn't come with curl installed.

In any case, I've updated the provision script to install curl, so this issue should be fixed.

**Comment by chokkoretto** [comment]
Okay still bumping my head into things.  When I run that command again, 
./extra/provision.sh -m prod -s $PWD
it ends at 
rm: cannot remove '/etc/nginx/sites-enabled/default': No such file or directory

I am assuming this is still not working out as the set password shows not found still.  
Sorry again for being so clueless here.

**Comment by gsingh93** [comment]
I think that's happening because of a bug when you run the script twice. I pushed a fix for that very recently, try doing a pull and running the script again.

**Comment by gsingh93** [comment]
Sorry, I had made the commit locally, but forgot to push it. I just pushed the fix: https://github.com/facebook/fbctf/commit/6ea78941136d719cd76658e73390d5e24c196925
