### ISSUE TITLE
Log-in not working

### ISSUE THREAD

**Issue by ethanaldrich9986** [facebook/fbctf#558]
When using the latest master branch and setting up using the script in just normal ubuntu server 14.04, I added ubuntu-desktop, then opened Firefox and tried to log-in. When I did, the button does not do anything. Help?

**Comment by justinwray** [comment]
To better assist you with troubleshooting this issue we will need some additional information, namely the exact provision options used and the output of the provision log.  In this case, client side console output (the errors) would also be helpful.

However, even without that information this very likely caused by some node installation and module issues that have been addressed in the `dev` branch.  Those fixes are in the process of being merged into `master`, so you may want to give the updated code a try once it is committed.

**Comment by peternguyen93** [comment]
I have same problem when I running grunt --force :
`Logs will go to /tmp/flow/zSvarzSwwwzSfbctfzSsrc.log
Started a new flow server: -flow is still initializing; this can take some time. [processing] \flow is still initializing; this can take some time. [processing] |flow is still initializing; this can take some time. [merging inference] /Error: src/static/js/admin.js:5
  5: var Dropkick = require('dropkickjs');
                            ^^^^^^^^^^^^ dropkickjs. Required module not found

Error: src/static/js/admin.js:6
  6: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

Error: src/static/js/admin.js:1077
1077:         createTokens($section);
                           ^^^^^^^^ unused function argument
       v------------------------
  578: function createTokens() {
  579:   var create_data = {
  580:     action: 'create_tokens'
  ...:
  583: }
       ^ function expects no arguments

Error: src/static/js/admin.js:1079
1079:         exportTokens($section);
                           ^^^^^^^^ unused function argument
       v------------------------
  586: function exportTokens() {
  587:   var csrf_token = $('input[name=csrf_token]')[0].value;
  588:   var action = 'export_tokens';
  ...:
  591: }
       ^ function expects no arguments

Error: src/static/js/clock.js:3
  3: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

Error: src/static/js/fb-ctf.js:12
 12: var d3 = require('d3');
                      ^^^^ d3. Required module not found

Error: src/static/js/fb-ctf.js:13
 13: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found

Error: src/static/js/fb-ctf.js:14
 14: var Keycode = require('keycode');
                           ^^^^^^^^^ keycode. Required module not found

Error: src/static/js/fb-ctf.js:809
809:           launchCaptureModal(country, capturedBy);
                                           ^^^^^^^^^^ unused function argument
           v-------------------------------------
  883:     function launchCaptureModal(country) {
  884:       var data = FB_CTF.data.COUNTRIES[country];
  885:
  ...:
  1044:     } // function launchCaptureModal();
            ^ function expects no more than 1 argument

Error: src/static/js/filter.js:3
  3: var $ = require('jquery');
                     ^^^^^^^^ jquery. Required module not found


Found 10 errors
Warning: non-zero exit code 2 Use --force to continue.`

That leads to no file in static/dist/js/app.js is generated so Login Button is not work now

**Comment by ethanaldrich9986** [comment]
I have the app.js file and it still won't let you log in. @justinwray What logs should I upload for you?

**Comment by justinwray** [comment]
@ethanaldrich9986 / @peternguyen93 / Others:

The `master` branch was just updated with some fixes to the failing build process.  Please try the setup process again and see if the new updates have resolved your issue.  Take a look at the [Quick Setup Guide](https://github.com/facebook/fbctf/wiki/Quick-Setup-Guide) as well.

**Comment by juanrossi** [comment]
Hello, in my case the login works correctly, but only when the user and password are correct. The index.js has some issues regarding input names.

Example, line 39 of index.js:

    var teamName = String($('.fb-form input[name="teamname"]')[0].value);

Should be:

    var teamName = String($('.fb-form input[name="team_name"]')[0].value);

When that is fix other errors are shown.

**Comment by 15w34r0n3D4y** [comment]
Can someone help, how fix it i have problem like @peternguyen93?
Problem when install:

Install npm, a package manager for JavaScript:

sudo apt-get install npm

Update npm:

sudo npm install -g npm@lts

Install nodejs-legacy, a server-side JavaScript environment:

sudo apt-get install nodejs-legacy

Install npm modules required by the platform:

sudo npm install --prefix /var/www/fbctf
sudo npm install -g grunt
sudo npm install -g flow-bin

Run grunt to generate JavaScript files:

cd /var/www/fbctf
grunt 

can't run grunt - 10errors, I try on Ubuntu 14.04 and Debian 7. 
Page is white.

I wanna use **Provision Script Details**

**Comment by 15w34r0n3D4y** [comment]
@justinwray can for Debian too, please. Thank you for script.

**Comment by stevcoll** [comment]
Please open a new issue if any of you are having continued problems with the latest fixes.
